name: keycloak-baeldung-bff
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: 
      - start-dev
    secrets:
      - source: server_crt
        target: /etc/x509/https/tls.crt
      - source: server_key
        target: /etc/x509/https/tls.key
    ports:
      #- 8080:8080
      - 8443:8443
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      #KC_HTTP_PORT: 8080
      KC_HTTPS_PORT: 8443
      KC_HOSTNAME_URL: https://localhost:7080/auth
      KC_HOSTNAME_ADMIN_URL: https://localhost:7080/auth
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      KC_HTTP_RELATIVE_PATH: /auth
      #KC_LOG_LEVEL: DEBUG
    container_name: keycloak-baeldung-bff

secrets:
  server_crt:
    file: ./ssl/self_signed.crt
  server_key:
    file: ./ssl/req_key.pem
